"""empty message

Revision ID: 23553eca9bb7
Revises: 418e5d6143ff
Create Date: 2020-02-28 00:02:06.051345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23553eca9bb7'
down_revision = '418e5d6143ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=True),
    sa.Column('project_description', sa.String(length=300), nullable=True),
    sa.Column('cost', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('reach', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity')
    # ### end Alembic commands ###
